server:
  port: 8080

spring:
  application:
    name: blcks-java-spring-wuphf

---
spring:
  config:
    activate:
      on-profile: memory
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.liquibase.LiquibaseAutoConfiguration

---
spring:
  config:
    activate:
      on-profile: database
  datasource:
    url: jdbc:postgresql://${BLCKS_DATABASE1_HOST}:${BLCKS_DATABASE1_PORT}/${BLCKS_DATABASE1_WUPHF_DATABASE}
    username: ${BLCKS_DATABASE1_WUPHF_USER}
    password: ${BLCKS_DATABASE1_WUPHF_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
